### ISSUE TITLE
Style.Css not working

### ISSUE THREAD

**Issue by littl3lionwoman** [johnpbloch/child-themify#13]
Hi, I thought the purpose of a child theme was to pull the child theme stylesheet before the stylesheet of the Template theme. I don't know if this is being over-ridden, or what the issue could be, but if I go to Editor > Style.css in my child theme it doesn't read any of the code I'm putting in there.

Could you please tell me why this isn't working?

**Comment by CubeProMH** [comment]
The new child theme standards do not recognize the `@import` css rule

It is now required to use a  functions.php file and have this code to import the styles

```
<?php
function my_theme_enqueue_styles() {

    $parent_style = 'parent-style';

    wp_enqueue_style( $parent_style, get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array( $parent_style )
    );
}
add_action( 'wp_enqueue_scripts', 'my_theme_enqueue_styles' );
?>
```

read more here [https://codex.wordpress.org/Child_Themes](https://codex.wordpress.org/Child_Themes)

I have attached a very generic function.php file that I currently use in my child themes

[functions.zip](https://github.com/johnpbloch/child-themify/files/388688/functions.zip)

**Comment by johnpbloch** [comment]
@littl3lionwoman child themes are supposed to load their styles after the parent theme's styles.

@CubeProMH I've already looked into switching out the `@import` uses and came to the conclusion that it didn't make sense to do so. You can read more of my reasoning [in this support forum post](https://wordpress.org/support/topic/import-is-not-used-anymore?replies=3)
